services:
  # Backend Service
  - type: web
    name: calyx-ai-backend
    env: python
    region: singapore
    plan: free
    rootDir: Backend
    buildCommand: python -m pip install --upgrade pip && pip install -r Requirements.txt
    startCommand: gunicorn server:app --workers 1 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        value: https://calyx-ai-project.vercel.app
      - key: GEMINI_API_KEY
        value: ""
      - key: HuggingFaceAPIKey
        value: ""
      - key: GroqAPIKey
        value: ""
      - key: CohereAPIKey
        value: ""
      - key: JWT_SECRET
        value: "generate_a_random_string_here"
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""
      - key: GITHUB_CLIENT_ID
        value: ""
      - key: GITHUB_CLIENT_SECRET
        value: ""
