services:
  # Backend Service
  - type: web
    name: calyx-ai-backend
    env: python
    region: singapore
    plan: free
    rootDir: Backend
    buildCommand: python -m pip install --upgrade pip && pip install -r Requirements.txt
    startCommand: gunicorn server:app --workers 1 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        value: https://calyx-ai-project.vercel.app
      - key: GEMINI_API_KEY
        value: ""
      - key: HuggingFaceAPIKey
        value: ""
      - key: GroqAPIKey
        value: ""
      - key: CohereAPIKey
        value: ""
      - key: JWT_SECRET
        value: "generate_a_random_string_here"
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""
      - key: BACKEND_URL
        value: https://calyx-ai-backend-wl72.onrender.com
      - key: GITHUB_CLIENT_ID
        value: "Ov23liKDmOMm3PP5smzp"
      - key: GITHUB_CLIENT_SECRET
        value: "f935bda0b6a999bcc82453be72472c27d445a64c"
      - key: SUPABASE_URL
        value: https://mfloiincuqomulvuekso.supabase.co
      - key: SUPABASE_ANON_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mbG9paW5jdXFvbXVsdnVla3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MjMyODksImV4cCI6MjA5MzM5OTI4OX0.4AOmuU9tMrvL_-cXs0XvsgnzIF8zEm-T3awA1mL5WYk"
